--liquibase formatted sql

--changeset company-vacancy-service:001-initial-schema
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'company'
CREATE TABLE company (
    company_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    inn         VARCHAR(255)  NOT NULL,
    kpp         VARCHAR(255)  NOT NULL,
    ogrn        VARCHAR(255)  NOT NULL,
    address     VARCHAR(1000) NOT NULL,
    director    VARCHAR(255)  NOT NULL,
    date_reg    TIMESTAMP(6)  NOT NULL,
    is_accepted BOOLEAN,
    user_name   VARCHAR(255)
);

CREATE TABLE vacancy (
    vacancy_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    title       VARCHAR(255)  NOT NULL,
    description VARCHAR(1000),
    company_id  BIGINT        NOT NULL REFERENCES company (company_id),
    contact     VARCHAR(255)  NOT NULL,
    experience  VARCHAR(1000),
    format      VARCHAR(255),
    address     VARCHAR(1000),
    schedule    VARCHAR(255),
    hours       VARCHAR(255),
    is_educated BOOLEAN,
    is_hidden   BOOLEAN,
    date        TIMESTAMP(6)  NOT NULL
);

CREATE TABLE response (
    response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        TIMESTAMP(6) NOT NULL,
    user_name   VARCHAR(255) NOT NULL,
    vacancy_id  BIGINT REFERENCES vacancy (vacancy_id) ON DELETE SET NULL,
    is_viewed   BOOLEAN      NOT NULL
);
--rollback DROP TABLE response; DROP TABLE vacancy; DROP TABLE company;
