--liquibase formatted sql

--changeset auth-service:001-initial-schema
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'user'
CREATE TABLE role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255) NOT NULL
);

CREATE TABLE "user" (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         VARCHAR(255) NOT NULL UNIQUE,
    pending_login VARCHAR(255),
    password      VARCHAR(255) NOT NULL,
    role_id       BIGINT       NOT NULL REFERENCES role (role_id),
    enabled       BOOLEAN      NOT NULL
);

-- resume_id совпадает с user_id (связь один-к-одному через @MapsId)
CREATE TABLE resume (
    resume_id       BIGINT PRIMARY KEY REFERENCES "user" (user_id),
    education       VARCHAR(255)  NOT NULL,
    place_education VARCHAR(255)  NOT NULL,
    skills          VARCHAR(255),
    birthday        TIMESTAMP(6),
    gender          VARCHAR(255)  NOT NULL,
    full_name       VARCHAR(255)  NOT NULL,
    phone           VARCHAR(255),
    contact         VARCHAR(255),
    description     VARCHAR(2000),
    date            TIMESTAMP(6)  NOT NULL
);

CREATE TABLE resume_image (
    resume_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url             VARCHAR(255) NOT NULL,
    resume_id       BIGINT       NOT NULL REFERENCES resume (resume_id)
);
--rollback DROP TABLE resume_image; DROP TABLE resume; DROP TABLE "user"; DROP TABLE role;

--changeset auth-service:002-seed-roles
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM role
-- Идентификаторы ролей используются в коде: 1 - администратор, 2 - пользователь, 3 - сотрудник
INSERT INTO role (role_id, title) VALUES
    (1, 'Администратор'),
    (2, 'Пользователь'),
    (3, 'Сотрудник');
SELECT setval(pg_get_serial_sequence('role', 'role_id'), 3);
--rollback DELETE FROM role WHERE role_id IN (1, 2, 3);
